name: Firebase Continous Deployment

on:
  push: 
    branches: [ master ]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm install
      - run: npm run generate
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_HOSTING }}
          FIREBASE_PROJECT: atrapio-dev
